In [5]:
import pandas as pd

# multivariate data preparation
from numpy import array
from numpy import hstack

In [6]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [8]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
X, y = split_sequences(dataset, n_steps)
print(X.shape, y.shape)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

(7, 3, 2) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [3]:
df_merged_quandl = pd.read_csv(r".\cleaned_data\02. Quandl\df_merged_quandl.csv") # open the dataframe
df_merged_quandl

Date       M2  S&P 500      CPI   RE Loan  Initial Claims  \
0     1871-01-01      NaN   105.76      NaN       NaN             NaN   
1     1871-02-01      NaN   104.02      NaN       NaN             NaN   
2     1871-03-01      NaN   105.01      NaN       NaN             NaN   
3     1871-04-01      NaN   112.01      NaN       NaN             NaN   
4     1871-05-01      NaN   117.56      NaN       NaN             NaN   
...          ...      ...      ...      ...       ...             ...   
1845  2022-09-01  21459.5  3850.52  296.808  248786.1             NaN   
1846  2022-09-01  21459.5  3585.62  296.808  248786.1             NaN   
1847  2022-10-01  21362.5  3726.05  298.012  250692.6             NaN   
1848  2022-10-01  21362.5  3871.98  298.012  250692.6             NaN   
1849  2022-11-01      NaN  3856.10      NaN       NaN             NaN   

      Revolving Credit  index  PMI  
0                  NaN    NaN  NaN  
1                  NaN    NaN  NaN  
2                  NaN    NaN  NaN  
3                  NaN    NaN  NaN  
4                  NaN    NaN  NaN  
...                ...    ...  ...  
1845               NaN    NaN  NaN  
1846               NaN    NaN  NaN  
1847               NaN    NaN  NaN  
1848               NaN    NaN  NaN  
1849               NaN    NaN  NaN  

[1850 rows x 9 columns]

In [4]:
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

NameError: name 'array' is not defined